language: go
go:
  - "1.19"
  - "1.20"
  - "1.21"

stages:
  - name: quality

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

jobs:
  include:
    - stage: quality
      name: lint
      script: golangci-lint run
    - stage: quality
      name: unit-tests
      script: go test -v ./...